### ISSUE TITLE
How to add digital filter?

### ISSUE THREAD

**Issue by rmond18** [0015/ThatProject#19]
Hi, thank you so much for your work. It's awesome, I'm planning to add low pass filter in the ESP32_INMP441_BT_SERIAL_ARDUINO_IDE to remove the ambient/jittering noise, but I'm only a beginner and I'm not sure how and where to add the code for this. I don't have any idea how to start. If you could just point me in the right direction, maybe I'd manage.

Thank you again, keep up the good work!

**Comment by 0015** [comment]
@rmond18 I'd rather consider adding filtering in the app to handle it than adding filtering in ESP32. It's more restrictive in processing data in ESP32. If I have a chance, I'll try. Good luck!
